[workspace]
members = [
  "stats-reporter"
]

[workspace.dependencies]
reqwest = { version="0.11.25", default-features = false, features = ["rustls-tls"] }
sysinfo = "0.30.7"
tokio = { version = "1.36.0", features = ["full"] }

