[package]
name = "stats-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
axum.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
